#!/bin/bash

NAME="sales-system-app"
DIR=/home/pi/sales-system
USER=pi
GROUP=pi
WORKERS=3
BIND=unix:/home/pi/sales-system/run/sales-system.sock
DJANGO_SETTINGS_MODULE=sales.settings
DJANGO_WSGI_MODULE=sales.wsgi
LOG_LEVEL=error

cd $DIR
source venv/bin/activate

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

exec venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-
